export const constants = 
    [
        {
            "id": 1,
            "name": "Fastrack Zeal Black",
            "brand": "Fastrack",
            "model": "Zeal",
            "display_size": "4.69 cm",
            "display_type": "AMOLED",
            "description":"Reflex Play Plus- Smart Watch, Amoled Display, Period Tracker, & BT Calling",
            "features": [
                "Always-On Display (AOD)",
                "Functional Crown",
                "Bluetooth Calling"
            ],
            "strap_color": "Black",
            "strap_material": "Leather",
            "price": 2995.00,
            "original_price": 12995.00,
            "discount": "54%",
            "availability": "In stock",
            "delivery_date": "2024-08-05",
            "image_url": "https://www.fastrack.in/dw/image/v2/BKDD_PRD/on/demandware.static/-/Sites-titan-master-catalog/default/dw81d0352d/images/Fastrack/Catalog/3287KM06_1.jpg?sw=600&sh=600"
        },
        {
            "id": 2,
            "name": "Fastrack Zeal Brown",
            "brand": "Fastrack",
            "model": "Zeal",
            "display_size": "4.69 cm",
            "display_type": "AMOLED",
            "description":"Fastrack Vyb Halo Tees Quartz Analog Black Dial Silicone Strap Watch ",
            "features": [
                "Always-On Display (AOD)",
                "Functional Crown",
                "Bluetooth Calling"
            ],
            "strap_color": "Brown",
            "strap_material": "Leather",
            "price": 1990.00,
            "original_price": 12995.00,
            "discount": "54%",
            "availability": "In stock",
            "delivery_date": "2024-08-05",
            "image_url": "https://www.fastrack.in/dw/image/v2/BKDD_PRD/on/demandware.static/-/Sites-titan-master-catalog/default/dw155168d9/images/Fastrack/Catalog/3278SM03_1.jpg?sw=600&sh=600"
        },
        {
            "id": 3,
            "name": "Fastrack Zeal Black with Silver Dial",
            "brand": "Fastrack",
            "model": "Zeal",
            "display_size": "4.69 cm",
            "display_type": "AMOLED",
            "description": "Fastrack Quartz Analog Black Dial Stainless Steel Strap Watch ",
            "features": [
                "Always-On Display (AOD)",
                "Functional Crown",
                "Bluetooth Calling"
            ],
            "strap_color": "Black",
            "strap_material": "Leather",
            "price": 3200.00,
            "original_price": 12995.00,
            "discount": "54%",
            "availability": "In stock",
            "delivery_date": "2024-08-05",
            "image_url": "https://www.fastrack.in/dw/image/v2/BKDD_PRD/on/demandware.static/-/Sites-titan-master-catalog/default/dw08795a5f/images/Fastrack/Catalog/68011PP08_1.jpg?sw=600&sh=600"
        },
        {
            "id": 4,
            "name": "Sonata Zeal Brown with Silver Dial",
            "brand": "Sonata",
            "model": "Zeal",
            "display_size": "4.69 cm",
            "display_type": "AMOLED",
            "description":"Sonata Quartz Analog Champagne Dial Stainless Steel Strap Watch",
            "features": [
                "Always-On Display (AOD)",
                "Functional Crown",
                "Bluetooth Calling"
            ],
            "strap_color": "Brown",
            "strap_material": "Leather",
            "price": 2999.00,
            "original_price": 12995.00,
            "discount": "54%",
            "availability": "In stock",
            "delivery_date": "2024-08-05",
            "image_url": "https://www.sonatawatches.in/dw/image/v2/BKDD_PRD/on/demandware.static/-/Sites-titan-master-catalog/default/dw99bf9a3a/images/Sonata/Catalog/77085PP14W_1.jpg?sw=600&sh=600"
        },
        {
            "id": 5,
            "name": "Titan Zeal Black with Gold Dial",
            "brand": "Titan",
            "model": "Zeal",
            "display_size": "4.69 cm",
            "display_type": "AMOLED",
            "description":"Titan Smart Watch with 4.97 CM Super AMOLED Display | AI Voice Assistant",
            "features": [
                "Always-On Display (AOD)",
                "Functional Crown",
                "Bluetooth Calling"
            ],
            "strap_color": "Black",
            "strap_material": "Leather",
            "price": 4999.00,
            "original_price": 12995.00,
            "discount": "54%",
            "availability": "In stock",
            "delivery_date": "2024-08-05",
            "image_url": "https://www.titan.co.in/dw/image/v2/BKDD_PRD/on/demandware.static/-/Sites-titan-master-catalog/default/dw5dea78ac/images/Titan/Catalog/1639SM02_1.jpg?sw=600&sh=600"
        },
        {
            "id": 6,
            "name": "Sonata Zeal Brown with Gold Dial",
            "brand": "Sonata",
            "model": "Zeal",
            "display_size": "4.69 cm",
            "display_type": "AMOLED",
            "description":"Sonata Quartz Analog with Day and Date White Dial Stainless Steel Strap Watch for Men",
            "features": [
                "Always-On Display (AOD)",
                "Functional Crown",
                "Bluetooth Calling"
            ],
            "strap_color": "Brown",
            "strap_material": "Leather",
            "price": 2500.00,
            "original_price": 12995.00,
            "discount": "54%",
            "availability": "In stock",
            "delivery_date": "2024-08-05",
            "image_url": "https://www.sonatawatches.in/dw/image/v2/BKDD_PRD/on/demandware.static/-/Sites-titan-master-catalog/default/dw4bcefb11/images/Sonata/Catalog/77105SM12W_1.jpg?sw=600&sh=600"
        },
        {
            "id": 7,
            "name": "Sonata Zeal Black with Red Strap",
            "brand": "Sonata",
            "model": "Zeal",
            "display_size": "4.69 cm",
            "display_type": "AMOLED",
            "description":"Sonata Quartz Multifunction Black Dial Black Leather Strap Watch For Men",
            "features": [
                "Always-On Display (AOD)",
                "Functional Crown",
                "Bluetooth Calling"
            ],
            "strap_color": "Red",
            "strap_material": "Leather",
            "price": 1995.00,
            "original_price": 12995.00,
            "discount": "54%",
            "availability": "In stock",
            "delivery_date": "2024-08-05",
            "image_url": "https://www.sonatawatches.in/dw/image/v2/BKDD_PRD/on/demandware.static/-/Sites-titan-master-catalog/default/dw640333ef/images/Sonata/Catalog/SP70019QP01W_1.jpg?sw=600&sh=600"
        },
        {
            "id": 8,
            "name": "Sonata Zeal Brown with Red Strap",
            "brand": "Sonata",
            "model": "Zeal",
            "display_size": "4.69 cm",
            "display_type": "AMOLED",
            "description":"Sonata Blues Quartz Analog Blue Dial Metal Strap Watch for Men",
            "features": [
                "Always-On Display (AOD)",
                "Functional Crown",
                "Bluetooth Calling"
            ],
            "strap_color": "Red",
            "strap_material": "Leather",
            "price": 2999.00,
            "original_price": 12995.00,
            "discount": "54%",
            "availability": "In stock",
            "delivery_date": "2024-08-05",
            "image_url": "https://www.sonatawatches.in/dw/image/v2/BKDD_PRD/on/demandware.static/-/Sites-titan-master-catalog/default/dwfe452d5a/images/Sonata/Catalog/7149QM01_1.jpg?sw=600&sh=600"
        },
        {
            "id": 9,
            "name": "Titan Zeal Black with Blue Strap",
            "brand": "Titan",
            "model": "Zeal",
            "display_size": "4.69 cm",
            "display_type": "AMOLED",
            "description": "Titan Edge Baseline Grey Dial Analog Stainless Steel Strap watch for Men",
            "features": [
                "Always-On Display (AOD)",
                "Functional Crown",
                "Bluetooth Calling"
            ],
            "strap_color": "Blue",
            "strap_material": "Leather",
            "price": 5995.00,
            "original_price": 12995.00,
            "discount": "54%",
            "availability": "In stock",
            "delivery_date": "2024-08-05",
            "image_url": "https://www.titan.co.in/dw/image/v2/BKDD_PRD/on/demandware.static/-/Sites-titan-master-catalog/default/dw66802566/images/Titan/Catalog/1878KD03_1.jpg?sw=360&sh=360"
        },
        {
            "id": 10,
            "name": "Titan Zeal Brown with Blue Strap",
            "brand": "Titan",
            "model": "Zeal",
            "display_size": "4.69 cm",
            "display_type": "AMOLED",
            "description": "Titan Raga Showstopper Quartz Analog Rose Gold Dial Metal Strap Watch for Women",
            "features": [
                "Always-On Display (AOD)",
                "Functional Crown",
                "Bluetooth Calling"
            ],
            "strap_color": "Blue",
            "strap_material": "Leather",
            "price": 5995.00,
            "original_price": 12995.00,
            "discount": "54%",
            "availability": "In stock",
            "delivery_date": "2024-08-05",
            "image_url": "https://www.titan.co.in/dw/image/v2/BKDD_PRD/on/demandware.static/-/Sites-titan-master-catalog/default/dw0713b276/images/Titan/Catalog/95283WM01_1.jpg?sw=600&sh=600"
        },
        {
            "id": 11,
            "name": "Fastrack Zeal Black with Green Strap",
            "brand": "Fastrack",
            "model": "Zeal",
            "display_size": "4.69 cm",
            "display_type": "AMOLED",
            "description": "Fastrack Quartz Analog Black Dial Black Stainless Steel Strap Watch for Guys",
            "features": [
                "Always-On Display (AOD)",
                "Functional Crown",
                "Bluetooth Calling"
            ],
            "strap_color": "Green",
            "strap_material": "Leather",
            "price": 5995.00,
            "original_price": 12995.00,
            "discount": "54%",
            "availability": "In stock",
            "delivery_date": "2024-08-05",
            "image_url": "https://www.fastrack.in/dw/image/v2/BKDD_PRD/on/demandware.static/-/Sites-titan-master-catalog/default/dw6f51faf6/images/Fastrack/Catalog/38022PP10J_1.jpg?sw=360&sh=360"
        },
        {
            "id": 12,
            "name": "Fastrack Zeal Brown Strap",
            "brand": "Fastrack",
            "model": "Zeal",
            "display_size": "4.69 cm",
            "display_type": "AMOLED",
            "description": "Fastrack Tick Tock Quartz Analog Black Dial With Black Stainless steel Strap Watch for Guys",
            "features": [
                "Always-On Display (AOD)",
                "Functional Crown",
                "Bluetooth Calling"
            ],
            "strap_color": "Green",
            "strap_material": "Leather",
            "price": 5995.00,
            "original_price": 12995.00,
            "discount": "54%",
            "availability": "In stock",
            "delivery_date": "2024-08-05",
            "image_url": "https://www.fastrack.in/dw/image/v2/BKDD_PRD/on/demandware.static/-/Sites-titan-master-catalog/default/dwb1aca471/images/Fastrack/Catalog/68012PP03_1.jpg?sw=360&sh=360"
        },
        {
            "id": 13,
            "name": "Titan Zeal Black with Yellow Strap",
            "brand": "Titan",
            "model": "Zeal",
            "display_size": "4.69 cm",
            "display_type": "AMOLED",
            "features": [
                "Always-On Display (AOD)",
                "Functional Crown",
                "Bluetooth Calling"
            ],
            "strap_color": "Yellow",
            "strap_material": "Leather",
            "price": 5995.00,
            "original_price": 12995.00,
            "discount": "54%",
            "availability": "In stock",
            "delivery_date": "2024-08-05",
            "image_url": "https://example.com/image13.png"
        },
        {
            "id": 14,
            "name": "Titan Zeal Brown with Yellow Strap",
            "brand": "Titan",
            "model": "Zeal",
            "display_size": "4.69 cm",
            "display_type": "AMOLED",
            "features": [
                "Always-On Display (AOD)",
                "Functional Crown",
                "Bluetooth Calling"
            ],
            "strap_color": "Yellow",
            "strap_material": "Leather",
            "price": 5995.00,
            "original_price": 12995.00,
            "discount": "54%",
            "availability": "In stock",
            "delivery_date": "2024-08-05",
            "image_url": "https://example.com/image14.png"
        },
        {
            "id": 15,
            "name": "Titan Zeal Black with Purple Strap",
            "brand": "Titan",
            "model": "Zeal",
            "display_size": "4.69 cm",
            "display_type": "AMOLED",
            "features": [
                "Always-On Display (AOD)",
                "Functional Crown",
                "Bluetooth Calling"
            ],
            "strap_color": "Purple",
            "strap_material": "Leather",
            "price": 5995.00,
            "original_price": 12995.00,
            "discount": "54%",
            "availability": "In stock",
            "delivery_date": "2024-08-05",
            "image_url": "https://example.com/image15.png"
        },
        {
            "id": 16,
            "name": "Titan Zeal Brown with Purple Strap",
            "brand": "Titan",
            "model": "Zeal",
            "display_size": "4.69 cm",
            "display_type": "AMOLED",
            "features": [
                "Always-On Display (AOD)",
                "Functional Crown",
                "Bluetooth Calling"
            ],
            "strap_color": "Purple",
            "strap_material": "Leather",
            "price": 5995.00,
            "original_price": 12995.00,
            "discount": "54%",
            "availability": "In stock",
            "delivery_date": "2024-08-05",
            "image_url": "https://example.com/image16.png"
        },
        {
            "id": 17,
            "name": "Titan Zeal Black with Orange Strap",
            "brand": "Titan",
            "model": "Zeal",
            "display_size": "4.69 cm",
            "display_type": "AMOLED",
            "features": [
                "Always-On Display (AOD)",
                "Functional Crown",
                "Bluetooth Calling"
            ],
            "strap_color": "Orange",
            "strap_material": "Leather",
            "price": 5995.00,
            "original_price": 12995.00,
            "discount": "54%",
            "availability": "In stock",
            "delivery_date": "2024-08-05",
            "image_url": "https://example.com/image17.png"
        },
        {
            "id": 18,
            "name": "Titan Zeal Brown with Orange Strap",
            "brand": "Titan",
            "model": "Zeal",
            "display_size": "4.69 cm",
            "display_type": "AMOLED",
            "features": [
                "Always-On Display (AOD)",
                "Functional Crown",
                "Bluetooth Calling"
            ],
            "strap_color": "Orange",
            "strap_material": "Leather",
            "price": 5995.00,
            "original_price": 12995.00,
            "discount": "54%",
            "availability": "In stock",
            "delivery_date": "2024-08-05",
            "image_url": "https://example.com/image18.png"
        },
        {
            "id": 19,
            "name": "Titan Zeal Black with Pink Strap",
            "brand": "Titan",
            "model": "Zeal",
            "display_size": "4.69 cm",
            "display_type": "AMOLED",
            "features": [
                "Always-On Display (AOD)",
                "Functional Crown",
                "Bluetooth Calling"
            ],
            "strap_color": "Pink",
            "strap_material": "Leather",
            "price": 5995.00,
            "original_price": 12995.00,
            "discount": "54%",
            "availability": "In stock",
            "delivery_date": "2024-08-05",
            "image_url": "https://example.com/image19.png"
        },
        {
            "id": 20,
            "name": "Titan Zeal Brown with Pink Strap",
            "brand": "Titan",
            "model": "Zeal",
            "display_size": "4.69 cm",
            "display_type": "AMOLED",
            "features": [
                "Always-On Display (AOD)",
                "Functional Crown",
                "Bluetooth Calling"
            ],
            "strap_color": "Pink",
            "strap_material": "Leather",
            "price": 5995.00,
            "original_price": 12995.00,
            "discount": "54%",
            "availability": "In stock",
            "delivery_date": "2024-08-05",
            "image_url": "https://example.com/image20.png"
        }
    ]